# Setup
title:        Open Rec
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      /openrec-demo
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://christinatsan.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown



