# Setup
title:        Open Rec
tagline:      An open-source modular framework for recommendation and personalization
baseurl:      /openrec-demo
paginate:     1
published: false

# About/contact
author:
  name:       Small Data Lab
  url:        http://christinatsan.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown



