# Setup
title:        OpenRec
tagline:      An open-source modular framework for recommendation and personalization
baseurl:      "/"
paginate:     1
published: false

# About/contact
author:
  name:       Small Data Lab
  url:        http://christinatsan.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown



